<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Infra\Database\Inss.ProjectStructureExample.Infra.Database\Inss.ProjectStructureExample.Infra.Database.csproj" />
    <ProjectReference Include="..\..\Api\Inss.ProjectStructureExample.Web.Api.WebApi\Inss.ProjectStructureExample.Web.Api.WebApi.csproj" />
  </ItemGroup>

</Project>
